version: '2'
services:
  db:
    image: postgres:11-alpine
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_DB=marvel_superhero
    - POSTGRES_USER=vrushali
    - POSTGRES_PASSWORD=vrushali

  kf:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - ADVERTISED_HOST=0.0.0.0
      - ADVERTISED_PORT=9092